# Generated by Django 4.1.5 on 2023-03-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_carts_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
