# Generated by Django 4.1.5 on 2023-03-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default={}, upload_to='products/'),
            preserve_default=False,
        ),
    ]
